### ISSUE TITLE
Increasing redemption fee incorrectly updates the fee paid

### ISSUE THREAD

**Issue by samczsun** [keep-network/tbtc#652]
# Description
When performing a withdrawal, the transaction fee (defined as the original amount of the UXTO minus the value transferred) is stored as a state variable.

https://github.com/keep-network/tbtc/blob/100e5aae60aad209b0d3c6d495438d2b5b270fd3/solidity/contracts/deposit/DepositRedemption.sol#L110

https://github.com/keep-network/tbtc/blob/100e5aae60aad209b0d3c6d495438d2b5b270fd3/solidity/contracts/deposit/DepositRedemption.sol#L123

This variable is checked when submitting a redemption proof, to make sure that the signers didn't change the fee amount (thereby causing a loss to the user).

https://github.com/keep-network/tbtc/blob/100e5aae60aad209b0d3c6d495438d2b5b270fd3/solidity/contracts/deposit/DepositRedemption.sol#L313

A user is allowed to increase the redemption fee after a certain time has passed, in case the blockchain is congested. If this happens, the transaction fee is updated to be the output of `checkRelationshipToPrevious`.

https://github.com/keep-network/tbtc/blob/100e5aae60aad209b0d3c6d495438d2b5b270fd3/solidity/contracts/deposit/DepositRedemption.sol#L232-L233

However, the above function does not return the fee, but rather the value being sent to the user.
https://github.com/keep-network/tbtc/blob/100e5aae60aad209b0d3c6d495438d2b5b270fd3/solidity/contracts/deposit/DepositRedemption.sol#L259-L281

# Exploit Scenario
If all of the members of the keep are able to collude then they may be able to grief the depositor. If a miner is involved, they may be able to recover some of the BTC from the depositor. Of course, in both cases the members risk getting slashed for fraud so this exploit scenario isn't very probable.

# Suggested Remediation
Set the fee paid to the correct value.

**Comment by sr-gi** [comment]
Came to report the same bug. I was wondering what the viability of this would be though, since I think it looks less severe that what it actually could be.

The signers would risk loss of funds for the minimum confirmation time, i.e. 6 blocks. However, this implies that there is a party that knows the funding UTXO and the original requested fee (either the redeemer or someone monitoring the calls to the contract) and that is also monitoring the Bitcoin blockchain in order to notice that the fraudulent transaction has a higher fee than expected.

Anyway, nice catch.

**Comment by Shadowfiend** [comment]
> The signers would risk loss of funds for the minimum confirmation time, i.e. 6 blocks

Can you explain this one? The issue here is that the available fee effectively goes from the initial fee to the full value of the deposit, but that means any transaction will pass redemption checks as long as it spends the right UTXO, right? My impression here is the signers are never at risk, whereas the redeemer could lose funds if a miner sees the fee bump and decides to mine a version of the transaction that sends the whole value as a fee.

**Comment by sr-gi** [comment]
> Can you explain this one? The issue here is that the available fee effectively goes from the initial fee to the full value of the deposit, but that means any transaction will pass redemption checks as long as it spends the right UTXO, right? 

Right, since after one fee bump the contract will store the new value as the fee, any submitted transaction will pass redemption checks. However, not any transaction is authorised. In this case the only two authorised txs would be the initial one, and the first fee bump which increased the feee by the same amount as the one set by the redeemer.

If signers collude, as originally stated, they could sign a third version of the transaction that swipes all funds for fees and that will pass the redemption checks. However they have to wait for the minimum confirmation time in order to provide the proof. In that time someone monitoring the contract and the Bitcoin blockchain can provide a fraud proof of their all-fee-transaction.

**Comment by Shadowfiend** [comment]
Ah yes, sorry, I didn't look closely enough to realize the approved signature in this case is correct, it's *only* the fee that is incorrectly read 👍
